In [47]:
#cleaning
import pandas as pd
import numpy as np
pd.options.display.max_rows = 999

In [48]:
df = pd.read_csv('exoplanet_data.csv')

In [49]:
df.head()

,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbsmaxlim,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,2,1,326.03000,0.32,-0.32,0.0,1.29,0.05,-0.05,0.0,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,1,1,516.21997,3.20,-3.20,0.0,1.53,0.07,-0.07,0.0,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,1,1,185.84000,0.23,-0.23,0.0,0.83,NaN,NaN,0.0,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,1,1,1773.40002,2.50,-2.50,0.0,2.93,0.08,-0.08,0.0,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,3,1,798.50000,1.00,-1.00,0.0,1.66,0.03,-0.03,0.0,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

 Dictionary found here:
 https://exoplanetarchive.ipac.caltech.edu/docs/API_PS_columns.html

In [50]:
df.shape

(4352, 73)

In [51]:
df.describe()

,sy_snum,sy_pnum,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,pl_orbsmaxerr2,pl_orbsmaxlim,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
count,4352.000000,4352.000000,4.212000e+03,4.033000e+03,4.033000e+03,4212.000000,4208.000000,1959.000000,1958.000000,4208.000000,...,4255.000000,4240.000000,4232.000000,4226.000000,4242.000000,4218.000000,4204.000000,4199.000000,4194.000000,4194.000000
mean,1.112822,1.789982,2.057318e+03,9.443590e+02,-9.292684e+02,-0.000475,5.449871,0.366509,-0.343306,-0.000475,...,-38.619500,12.789385,0.104433,-0.106657,10.692984,0.042686,-0.042733,12.514740,0.000668,-0.000668
std,0.356702,1.170389,1.125204e+05,5.747658e+04,5.747555e+04,0.037744,92.424304,5.111086,5.103885,0.021798,...,175.639434,3.081354,0.135168,0.222960,3.031618,0.251442,0.260253,2.979509,0.002034,0.002034
min,1.000000,1.000000,9.070629e-02,0.000000e+00,-3.650000e+06,-1.000000,0.004400,0.000000,-200.000000,-1.000000,...,-2400.000000,0.872000,0.000000,-11.920000,-3.044000,0.011000,-9.995000,2.926270,0.000122,-0.063232
25%,1.000000,1.000000,4.464757e+00,1.633000e-05,-1.340000e-03,0.000000,0.052975,0.000785,-0.030000,0.000000,...,-18.594000,11.294750,0.030000,-0.126000,9.188000,0.020000,-0.032000,10.965600,0.000256,-0.000535
50%,1.000000,1.000000,1.176103e+01,1.000000e-04,-1.000000e-04,0.000000,0.101650,0.002500,-0.002500,0.000000,...,-5.574000,13.674000,0.080000,-0.080000,11.706500,0.023000,-0.023000,13.450800,0.000360,-0.000360
75%,1.000000,2.000000,4.168857e+01,1.300000e-03,-1.600000e-05,0.000000,0.265575,0.030000,-0.000793,0.000000,...,-0.798500,15.052000,0.126000,-0.030000,12.928750,0.032000,-0.020000,14.815900,0.000535,-0.000256
max,4.000000,8.000000,7.300000e+06,3.650000e+06,0.000000e+00,1.000000,3500.000000,200.000000,0.600000,0.000000,...,-0.000350,44.610000,2.820000,-0.001000,33.110000,9.995000,-0.011000,20.186100,0.063232,-0.000122

In [52]:
df.isna().sum()

sy_snum               0
sy_pnum               0
pl_orbper           140
pl_orbpererr1       319
pl_orbpererr2       319
pl_orbperlim        140
pl_orbsmax          144
pl_orbsmaxerr1     2393
pl_orbsmaxerr2     2394
pl_orbsmaxlim       144
pl_rade              14
pl_radeerr1        1070
pl_radeerr2        1070
pl_radelim           14
pl_radj              16
pl_radjerr1        1072
pl_radjerr2        1072
pl_radjlim           16
pl_bmasse            22
pl_bmasseerr1      2563
pl_bmasseerr2      2563
pl_bmasselim         22
pl_bmassj            22
pl_bmassjerr1      2563
pl_bmassjerr2      2563
pl_bmassjlim         22
pl_orbeccen         478
pl_orbeccenerr1    3162
pl_orbeccenerr2    3162
pl_orbeccenlim      478
pl_insol           1579
pl_insolerr1       1656
pl_insolerr2       1656
pl_insollim        1637
pl_eqt             1110
pl_eqterr1         3417
pl_eqterr2         3417
pl_eqtlim          1123
ttv_flag              0
st_teff             216
st_tefferr1         381
st_tefferr2         408
st_tefflim          216
st_rad              331
st_raderr1          490
st_raderr2          515
st_radlim           331
st_mass              21
st_masserr1         302
st_masserr2         327
st_masslim           21
st_met              388
st_meterr1          729
st_meterr2          729
st_metlim           388
st_logg             354
st_loggerr1         524
st_loggerr2         524
st_logglim          354
ra                    0
dec                   0
sy_dist               5
sy_disterr1          97
sy_disterr2          97
sy_vmag             112
sy_vmagerr1         120
sy_vmagerr2         126
sy_kmag             110
sy_kmagerr1         134
sy_kmagerr2         148
sy_gaiamag          153
sy_gaiamagerr1      158
sy_gaiamagerr2      158
dtype: int64

In [53]:
#this drops 10 columns from our dataframe.  Not a terrible loss!  
#From here we can imput our data better.
df = df.dropna(axis = 1, thresh = 2176)

In [54]:
df.isna().sum()

sy_snum              0
sy_pnum              0
pl_orbper          140
pl_orbpererr1      319
pl_orbpererr2      319
pl_orbperlim       140
pl_orbsmax         144
pl_orbsmaxlim      144
pl_rade             14
pl_radeerr1       1070
pl_radeerr2       1070
pl_radelim          14
pl_radj             16
pl_radjerr1       1072
pl_radjerr2       1072
pl_radjlim          16
pl_bmasse           22
pl_bmasselim        22
pl_bmassj           22
pl_bmassjlim        22
pl_orbeccen        478
pl_orbeccenlim     478
pl_insol          1579
pl_insolerr1      1656
pl_insolerr2      1656
pl_insollim       1637
pl_eqt            1110
pl_eqtlim         1123
ttv_flag             0
st_teff            216
st_tefferr1        381
st_tefferr2        408
st_tefflim         216
st_rad             331
st_raderr1         490
st_raderr2         515
st_radlim          331
st_mass             21
st_masserr1        302
st_masserr2        327
st_masslim          21
st_met             388
st_meterr1         729
st_meterr2         729
st_metlim          388
st_logg            354
st_loggerr1        524
st_loggerr2        524
st_logglim         354
ra                   0
dec                  0
sy_dist              5
sy_disterr1         97
sy_disterr2         97
sy_vmag            112
sy_vmagerr1        120
sy_vmagerr2        126
sy_kmag            110
sy_kmagerr1        134
sy_kmagerr2        148
sy_gaiamag         153
sy_gaiamagerr1     158
sy_gaiamagerr2     158
dtype: int64

In [55]:
#testing a thorough null filling method:  fill with previous values up to a point, 
#and then fill with the average
#if I have to, I'll return to this to clean it up, change parameters, etc
df = df.fillna(method = 'bfill', limit =25)
df = df.fillna(value = df.median())

In [56]:
df.isna().sum()

sy_snum           0
sy_pnum           0
pl_orbper         0
pl_orbpererr1     0
pl_orbpererr2     0
pl_orbperlim      0
pl_orbsmax        0
pl_orbsmaxlim     0
pl_rade           0
pl_radeerr1       0
pl_radeerr2       0
pl_radelim        0
pl_radj           0
pl_radjerr1       0
pl_radjerr2       0
pl_radjlim        0
pl_bmasse         0
pl_bmasselim      0
pl_bmassj         0
pl_bmassjlim      0
pl_orbeccen       0
pl_orbeccenlim    0
pl_insol          0
pl_insolerr1      0
pl_insolerr2      0
pl_insollim       0
pl_eqt            0
pl_eqtlim         0
ttv_flag          0
st_teff           0
st_tefferr1       0
st_tefferr2       0
st_tefflim        0
st_rad            0
st_raderr1        0
st_raderr2        0
st_radlim         0
st_mass           0
st_masserr1       0
st_masserr2       0
st_masslim        0
st_met            0
st_meterr1        0
st_meterr2        0
st_metlim         0
st_logg           0
st_loggerr1       0
st_loggerr2       0
st_logglim        0
ra                0
dec               0
sy_dist           0
sy_disterr1       0
sy_disterr2       0
sy_vmag           0
sy_vmagerr1       0
sy_vmagerr2       0
sy_kmag           0
sy_kmagerr1       0
sy_kmagerr2       0
sy_gaiamag        0
sy_gaiamagerr1    0
sy_gaiamagerr2    0
dtype: int64

In [57]:
df.to_csv('./backfill_mean_data.csv', index = False)